-- Script to create the Java DB sample database. Run in the db/external directory using
--
-- java -cp $DERBY_HOME/lib/derbytools.jar:$DERBY_HOME/lib/derby.jar org.apache.derby.tools.ij ../derby/etc/sample.sql

connect 'jdbc:derby://localhost:1527/petshopdb;create=true';

-- CREATE SCHEMA SAMPLE;

CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.connection.requireAuthentication', 'true');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.authentication.provider', 'BUILTIN');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.user.pet', 'pet');

disconnect;

-- in order to set the connection's default schema,
-- so we don't have to qualify the table and view names

connect 'jdbc:derby://localhost:1527/petshopdb' user 'pet' password 'pet';

 
DROP TABLE PET.ORDER_ITEM; -- ORD_CODE
DROP TABLE PET.ORDERS; -- USR_CODE
DROP TABLE PET.PRODUCT;
DROP TABLE PET.ADMIN_HISTORY; --ORD_CODE, ITM_CODE, USR_CODE
DROP TABLE PET.USERS;
DROP TABLE PET.CATEGORY; --IMG_CODE
DROP TABLE PET.IMAGE;

CREATE TABLE CATEGORY (
   CAT_CODE INTEGER PRIMARY KEY NOT NULL,   
   CAT_NAME VARCHAR(100),
   CAT_DESC VARCHAR(200),
   CAT_CHILD_CODE INTEGER NOT NULL,
   IMG_CODE  INTEGER NOT NULL ) ;
   


CREATE TABLE ORDERS(
   ORD_CODE INTEGER PRIMARY KEY NOT NULL,
   USR_CODE INTEGER NOT NULL,
   ORD_PRICE INTEGER NOT NULL,
   ORD_CREATED_ON DATE,
   ORD_MODIFIED_ON DATE,
   ORD_CREATED_BY INTEGER NOT NULL,
   ORD_MODIFIED_BY INTEGER NOT NULL);  
   
   
   
CREATE TABLE ORDER_ITEM (
   ITM_CODE INTEGER PRIMARY KEY  NOT NULL,
   ITM_NAME VARCHAR(100),
   ITM_QUANTITY INTEGER NOT NULL,
   ITM_PRICE INTEGER NOT NULL,
   ORD_CODE INTEGER NOT NULL,
   ITM_CREATED_ON DATE,
   ITM_MODIFIED_ON DATE,
   ITM_CREATED_BY INTEGER NOT NULL,
   ITM_MODIFIED_BY INTEGER NOT NULL) ;

CREATE TABLE IMAGE (
   IMG_CODE INTEGER PRIMARY KEY NOT NULL, 
   IMG_NAME VARCHAR(100),
   IMG_DESC VARCHAR(200),
   IMG_LOCATION VARCHAR(200),
   IMG_TYPE VARCHAR(1),
   IMG_FILE_TYPE VARCHAR(5)) ;
   


CREATE TABLE PRODUCT (
   PRD_CODE INTEGER PRIMARY KEY  NOT NULL,
   PRD_NAME VARCHAR(100),
   PRD_DESC VARCHAR(200),
   PRD_PRICE INTEGER NOT NULL,
   IMG_CODE INTEGER NOT NULL,
   CAT_CODE INTEGER NOT NULL) ;
   

 
   
CREATE TABLE USERS (
   USR_CODE INTEGER PRIMARY KEY NOT NULL,
   USR_NAME VARCHAR(100) NOT NULL,
   USR_PWD VARCHAR(100) NOT NULL,
   USR_ALIAS VARCHAR(50) NOT NULL,
   USR_TYPE VARCHAR(5),
   USR_MOBILE INTEGER NOT NULL,
   USR_EMAIL VARCHAR(75),
   USR_ADDRESS VARCHAR(200));

CREATE TABLE ADMIN_HISTORY (
   ADH_CODE INTEGER PRIMARY KEY  NOT NULL,
   ADH_ACTION VARCHAR(1),
   ORD_CODE INTEGER NOT NULL,
   ITM_CODE INTEGER NOT NULL,
   ITM_QUANTITY INTEGER NOT NULL,
   ITM_PRICE INTEGER NOT NULL,
   ADH_MODIFIED_ON DATE,
   ADH_MODIFIED_BY INTEGER NOT NULL);

ALTER TABLE CATEGORY ADD CONSTRAINT FK_CAT_IMG_CODE FOREIGN KEY (IMG_CODE) REFERENCES IMAGE (IMG_CODE);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_C_USR_CODE FOREIGN KEY (ORD_CREATED_BY) REFERENCES USERS (USR_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_M_USR_CODE FOREIGN KEY (ORD_MODIFIED_BY) REFERENCES USERS (USR_CODE);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_USR_CODE FOREIGN KEY (USR_CODE) REFERENCES USERS (USR_CODE);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ITM_ORD_CODE FOREIGN KEY (ORD_CODE) REFERENCES ORDERS (ORD_CODE);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ITM_C_USR_CODE FOREIGN KEY (ITM_CREATED_BY) REFERENCES USERS (USR_CODE);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ITM_M_USR_CODE FOREIGN KEY (ITM_MODIFIED_BY) REFERENCES USERS (USR_CODE);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRD_IMG_CODE FOREIGN KEY (IMG_CODE) REFERENCES IMAGE (IMG_CODE);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRD_CAT_CODE FOREIGN KEY (CAT_CODE) REFERENCES CATEGORY (CAT_CODE);

ALTER TABLE ADMIN_HISTORY ADD CONSTRAINT FK_ADH_ORD_CODE FOREIGN KEY (ORD_CODE) REFERENCES ORDERS (ORD_CODE);
ALTER TABLE ADMIN_HISTORY ADD CONSTRAINT FK_ADH_ITM_CODE FOREIGN KEY (ITM_CODE) REFERENCES ORDER_ITEM (ITM_CODE);
ALTER TABLE ADMIN_HISTORY ADD CONSTRAINT FK_ADH_M_USR_CODE FOREIGN KEY (ADH_MODIFIED_BY) REFERENCES USERS (USR_CODE);

COMMIT;

DISCONNECT;